import Game from './Game.js';

const choices = [
  "Knight or Dame loses seat",
  "Braverman loses seat",
  "Truss loses seat",
  "Sunak loses seat",
  "Jenrick loses seat",
  "Priti Patel loses seat",
  "Thérèse Coffey loses seat",
  "James Cleverly loses seat",
  "Rees-Mogg loses seat",
  "Shapps loses seat",
  "Mordaunt loses seat",
  "Tory moans about boundary changes",
  "Labour majority over 50",
  "Labour majority over 75",
  "Labour majority over 100",
  "Labour majority over 150",
  "Sunderland declares",
  "Newcastle declares",
  "Tory seat goes to Labour",
  "Tory seat goes to Lib Dem ",
  "Tory seat goes to Reform",
  "Small boats",
  "Rwanda",
  "Trussonomics",
  "Partygate",
  "Mention of Tony Blair",
  "Mention of John Major",
  "Mention of Boris Johnson ",
  "COVID",
  "‘Better than 1997’",
  "‘A landslide’",
  "‘Supermajority’",
  "‘Blue Wall’",
  "‘Red Wall’",
  "Tory insists ‘not what I heard on the doorstep’",
  "Candidate swears",
  "Sighting of Count Binface",
  "Drunk candidate interviewed",
  "Reform beaten by a joke candidate",
  "Greens win 1 seat",
  "Greens win 2 seats",
  "Greens win 3 seats",
  "Lib Dems win more than 50 seats",
  "Lib Dems win more than 60 seats"
];

const game = new Game(document.querySelector("#board"), choices);
