import Game from './Game.js';

const choices = [
  "A Sir or Dame loses their seat",
  "Braverman loses seat",
  "Truss loses seat",
  "Sunak loses seat",
  "Jenrick loses seat",
  "Priti Patel loses seat",
  "Therese Coffey loses seat",
  "James Cleverly loses seat",
  "Rees-Mogg loses seat",
  "Shapps loses seat",
  "A Tory moans about boundary changes",
  "Labour majority over 50",
  "Labour majority over 75",
  "Labour majority over 100",
  "Labour majority over 150",
  "Sunderland first to declare",
  "Newcastle first to declare",
  "Tory seat goes to Labour",
  "Tory seat goes to Lib Dem ",
  "Tory seat goes to Reform",
  "Tory seat flips to Labour for first time ever",
  "Small boats",
  "Rwanda",
  "Trussonomics",
  "Partygate",
  "Mention of Tony Blair",
  "Mention of John Major",
  "Mention of Boris Johnson ",
  "COVID",
  "‘Better than 1997’",
  "‘A landslide’",
  "‘Supermajority’",
  "‘Blue Wall’",
  "‘Red Wall’",
  "Tory insists ‘this is not what I heard on the doorstep’",
  "Candidate swears",
  "Sighting of Count Binface ",
  "Drunk candidate interviewed",
  "Reform beaten by a joke candidate in any seat",
  "Greens win 1 seat",
  "Greens win 2 seats",
  "Greens win 3 seats",
  "Lib Dems win more than 50 seats",
  "Lib Dems win more than 60 seats"
];

const game = new Game(document.querySelector("#board"), choices);
