import Game from './Game.js';

const choices = [
  "Suella Braverman loses seat",
  "Liz Truss loses seat",
  "Rishi Sunak loses seat",
  "Priti Patel loses seat",
  "Jacob Rees-Mogg loses seat",
  "Jeremy Hunt loses seat",
  "Tory moans about boundary changes",
  "Sunderland declares",
  "Newcastle declares",
  "Tory seat goes to Labour",
  "Tory seat goes to Lib Dem ",
  "Tory seat goes to Reform",
  "‘Small boats’",
  "‘Rwanda’",
  "‘Truss​onomics’",
  "‘Partygate’",
  "Tony Blair mentioned",
  "John Major mentioned",
  "Boris Johnson mentioned",
  "‘COVID’",
  "‘Better than 1997’",
  "‘Landslide’",
  "‘Super​majority’",
  "‘Blue Wall’",
  "‘Red Wall’",
  "Tory insists ‘not what I heard on the doorstep’",
  "Candidate swears",
  "Sighting of Count Binface",
  "Drunk candidate interviewed",
  "Reform beaten by a joke candidate",
  "Greens win a seat",
  "Lib Dems win more than 15 seats",
  "Islington North",
  "‘Portillo moment’",
  "‘Things Can Only Get Better’ played",
  "Tories come 4th in a seat",
  "‘Out of power for a generation’",
  "‘Canada 1993’",
  "Nigel Farage drinks a pint",
  "Dogs at polling stations",
  "‘Brexit’",
  "Tory candidate loses deposit",
  "Jeremy Corbin mentioned",
  "Tory blames voter ID",
  "Lettuce",
  "‘Father was a toolmaker’",
  "‘Woke’",
];

const game = new Game(document.querySelector("#board"), choices);
